spring:
  application:
    name: SERVICE-REGISTRY

  zipkin:
    base-url: http://127.0.0.1:9411/

server:
    port: 8761

#To disable eureka client behaviours
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# Actuator Prometheus Endpoints
management:
  endpoints:
    web:
      exposure:
        include: prometheus