spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/branch-microservice
    username: postgres
    password: Prami@3990

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8084

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/

message: Hello from branch-service now running on port 8081
